[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "devops-assignment"
version = "0.1.0"
description = "devops assigment"

[tool.setuptools]
packages = ["app"]

[tool.setuptools.package-data]
app = ["*"]