apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucube-app
  labels:
    app: ucube
spec: 
  selector:
    matchLabels:
      app: ucube
  template:
    metadata:
      labels:
        app: ucube
    spec:
      containers:
        - name: ucube-container
          image: 
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: ucube-service
spec:
  type: NodePort
  selector:
    app: ucube
  ports:
    - protocol: TCP
      port: 8000        
      targetPort: 8000  
      nodePort: 30008   

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ucube-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ucube-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85

